[project]
name = "pycharmprojects"
version = "0.1.0"
description = ""
authors = [
    {name = "someXXYY", email = "betaXXX@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.8.1"
dependencies = []

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{include = "pycharmprojects", from = "src"}]
package-mode = false

[tool.poetry.group.dev.dependencies]
flake8 = ">=6.0.0"

[tool.poetry.scripts]
allMyCats1 = "allMyCats1:main"
allMyCats2 = "allMyCats2:main"
backupToZip = "backupToZip:main"
birthdays = "birthdays:main"
boxPrint = "boxPrint:main"
buggyAddingProgram = "buggyAddingProgram:main"
bulletPointAdder = "bulletPointAdder:main"
calcProd = "calcProd:main"
catnapping = "catnapping:main"
census2010 = "census2010:main"
characterCount = "characterCount:main"
coinFlip = "coinFlip:main"
combinePdfs = "combinePdfs:main"
countdown = "countdown:main"
errorExample = "errorExample:main"
factorialLog = "factorialLog:main"
fiveTimes = "fiveTimes:main"
formFiller = "formFiller:main"
getDocxText = "getDocxText:main"
guessTheNumber = "guessTheNumber:main"
hello = "hello:main"
helloFunc = "helloFunc:main"
helloFunc2 = "helloFunc2:main"
inventory = "inventory:main"
isPhoneNumber = "isPhoneNumber:main"
littleKid = "littleKid:main"
lucky = "lucky:main"
magic8Ball = "magic8Ball:main"
magic8Ball2 = "magic8Ball2:main"
mapIt = "mapIt:main"
mcb = "mcb:main"
mouseNow = "mouseNow:main"
mouseNow2 = "mouseNow2:main"
multidownloadXkcd = "multidownloadXkcd:main"
myPets = "myPets:main"
passingReference = "passingReference:main"
phoneAndEmail = "phoneAndEmail:main"
picnicTable = "picnicTable:main"
prettyCharacterCount = "prettyCharacterCount:main"
printRandom = "printRandom:main"
quickWeather = "quickWeather:main"
randomQuizGenerator = "randomQuizGenerator:main"
readCensusExcel = "readCensusExcel:main"
readDocx = "readDocx:main"
removeCsvHeader = "removeCsvHeader:main"
renameDates = "renameDates:main"
resizeAndAddLogo = "resizeAndAddLogo:main"
sameName = "sameName:main"
sameName2 = "sameName2:main"
sameName3 = "sameName3:main"
sameName4 = "sameName4:main"
sendDuesReminders = "sendDuesReminders:main"
stopwatch = "stopwatch:main"
swordfish = "swordfish:main"
textMyself = "textMyself:main"
threadDemo = "threadDemo:main"
ticTacToe = "ticTacToe:main"
torrentStarter = "torrentStarter:main"
updateProduce = "updateProduce:main"
validateInput = "validateInput:main"
vampire = "vampire:main"
vampire2 = "vampire2:main"
zeroDivide = "zeroDivide:main"
downloadXkcd = "downloadXkcd:main"
