[project]
name = "automate-the-boring-stuff"
version = "0.1.0"
description = "Example scripts from Automate the Boring Stuff with Python"
authors = [
    {name = "someXXYY", email = "betaXXX@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.8.1"
dependencies = []

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{include = "automate_the_boring_stuff"}]

[tool.poetry.group.dev.dependencies]
flake8 = ">=6.0.0"
